# Generated by Django 4.2.5 on 2023-09-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_todos_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('publisher', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
