# Generated by Django 4.2.5 on 2023-09-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
