# Generated by Django 4.2.5 on 2023-09-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_books_author_alter_books_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
