# Generated by Django 4.2.5 on 2023-10-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_books_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
